package fr.insa.soa.ExchangeSemester.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import fr.insa.soa.ExchangeSemester.dao.UserRepository;
import fr.insa.soa.ExchangeSemester.model.User;

@RestController
public class LogInService {
	@Autowired
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@GetMapping("/loginService")
	public Iterable<User> test() {
		return userRepository.findAll();
	}
	
	@PostMapping("/loginService")
	public User testLogin(@RequestBody User user) {
		Iterable<User> itUser = userRepository.findAll();
		for(User users : itUser) {
			if(users.getLastName().equals(user.getLastName())) {
				System.out.println(users.getFirstName());
			}
		}
		
		return user;
	}
	
}
