package fr.insa.soa.ExchangeSemester.Services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import fr.insa.soa.ExchangeSemester.hello.User;
import fr.insa.soa.ExchangeSemester.hello.UserRepository;

@RestController
public class SignInService {

	@Autowired
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PutMapping("/signin")
	public String addAcount(@RequestBody User user) {
		boolean found = false;
		Iterable<User> listUsers = userRepository.findAll();

		for (User myUser : listUsers) {
			if (myUser.getLogin().equals(user.getLogin())) {
				found = true;
			}
		}

		if (found) {
			return "Login already used !";
		} else {
			userRepository.save(user);
			return "Signed in successfully !";
		}

	}
}