package fr.insa.soa.ExchangeSemester.restServices;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import fr.insa.soa.ExchangeSemester.dao.UniversityRepository;
import fr.insa.soa.ExchangeSemester.dao.UserRepository;
import fr.insa.soa.ExchangeSemester.dao.UserUniversityRepository;
import fr.insa.soa.ExchangeSemester.model.University;
import fr.insa.soa.ExchangeSemester.model.User;
import fr.insa.soa.ExchangeSemester.model.UserUniversity;
import fr.insa.soa.ExchangeSemester.services.UserService;

@RestController
public class UserRESTService {

	@Autowired
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(value = "/service/user", produces = "application/json")
	public List<User> test() {
		return userRepository.findAll();
	}

	@PutMapping(value = "/service/user", produces = "application/json")
	public String addAcount(@RequestBody User user) throws UnsupportedEncodingException, NoSuchAlgorithmException {
		UserService userService = new UserService(userRepository);

		boolean result = userService.saveUser(user);

		if (result) {
			return "{" + "\"success\": \"true\"," + "\"id\": \"" + user.getId() + "\"}";
		} else {
			return "{\"success\": \"false\"}";
		}
	}

	/*
	 * @DeleteMapping(value="/service/signup") public String
	 * deleteAccount(@RequestBody User user) { Iterable<User> listUsers =
	 * userRepository.findAll();
	 * 
	 * for (User myUser : listUsers) { if
	 * (myUser.getLogin().equals(user.getLogin())) { found = true; } } }
	 */

}